Tari=['Afganistan','Albania','Algeria','Argentina','Armenia','Australia','Austria','Belgia','Brazilia','Bulgaria','Canada','Cehia','Columbia','Croatia','Cuba','Danemarca','Egipt','Elvetia','Estonia','Franta','Finlanda','Germania','Grecia','India','Israel','Irlanda','Italia','Jamaica','Japonia','Madagascar','Mexic','Norvegia','Olanda','Polonia','Portugalia','Romania','Rusia','Serbia','Spania','Turcia','Ucraina','Ungaria']
Orase=['Atena','Bucuresti','Budapesta','Londra','Paris','Timisoara','Roma','Viena','Tokyo','Chisinau','Berlin','Arad','Brasov','Sibiu','Constanta','Oradea','Lugoj','Bistrita','Vaslui','Iasi','Resita']
Animale=['Caine','Pisica','Maimuta','Gaina','Cocos','Leu','Urs','Sarpe','Tigru','Caprioara','Iepure','Oaie','Girafa','Elefant','Foca','Paun','Crocodil']
Random=['hidrobicicleta','proiect','flaut','telefon','iaurt','covor','calculator','fotoliu','dupal','crizantema','boboc','creion']
Imagini=["hg1.png","hg2.png","hg3.png","hg4.png","hg5.png","hg6.png","hg7.png","hg8.png"]
